export const exercises = [
  {
    id: 1,
    title: "Sumar dos números",
    description:
      "Escribe una función que reciba dos números y retorne su suma.",
    starterCode: "def sumar(a, b):\\n    pass",
    language: "python",
    difficultyLevel: "Principiante",
    sequenceNumber: 1,
    isActive: true,
    createdAt: "2025-06-22T21:01:18.982+00:00",
    testCases: [
      {
        id: 4,
        inputData: "10 -7",
        expectedOutput: "3",
        isHidden: true,
        weight: 15,
      },
      {
        id: 5,
        inputData: "100 200",
        expectedOutput: "300",
        isHidden: true,
        weight: 30,
      },
      {
        id: 1,
        inputData: "2 3",
        expectedOutput: "5",
        isHidden: false,
        weight: 20,
      },
      {
        id: 3,
        inputData: "-5 3",
        expectedOutput: "-2",
        isHidden: false,
        weight: 20,
      },
      {
        id: 2,
        inputData: "0 0",
        expectedOutput: "0",
        isHidden: false,
        weight: 15,
      },
    ],
  },
  {
    id: 2,
    title: "Contar vocales",
    description:
      "Crea una función que cuente las vocales en una cadena de texto.",
    starterCode: "def contar_vocales(texto):\\n    pass",
    language: "python",
    difficultyLevel: "Intermedio",
    sequenceNumber: 2,
    isActive: true,
    createdAt: "2025-06-22T21:01:18.982+00:00",
    testCases: [
      {
        id: 10,
        inputData: "Murcielago",
        expectedOutput: "5",
        isHidden: true,
        weight: 10,
      },
      {
        id: 8,
        inputData: "xyz",
        expectedOutput: "0",
        isHidden: false,
        weight: 15,
      },
      {
        id: 7,
        inputData: "programacion",
        expectedOutput: "5",
        isHidden: false,
        weight: 20,
      },
      {
        id: 9,
        inputData: "AEIOU",
        expectedOutput: "5",
        isHidden: false,
        weight: 20,
      },
      {
        id: 12,
        inputData: "El perro ladra fuerte",
        expectedOutput: "7",
        isHidden: true,
        weight: 20,
      },
      {
        id: 11,
        inputData: "",
        expectedOutput: "0",
        isHidden: true,
        weight: 10,
      },
      {
        id: 6,
        inputData: "hola",
        expectedOutput: "2",
        isHidden: false,
        weight: 15,
      },
    ],
  },
  {
    id: 3,
    title: "Verificar número primo",
    description: "Implementa una función que determine si un número es primo.",
    starterCode: "def es_primo(n):\\n    pass",
    language: "python",
    difficultyLevel: "Avanzado",
    sequenceNumber: 3,
    isActive: true,
    createdAt: "2025-06-22T21:01:18.982+00:00",
    testCases: [
      {
        id: 13,
        inputData: "2",
        expectedOutput: "True",
        isHidden: false,
        weight: 15,
      },
      {
        id: 19,
        inputData: "97",
        expectedOutput: "True",
        isHidden: true,
        weight: 10,
      },
      {
        id: 20,
        inputData: "100",
        expectedOutput: "False",
        isHidden: true,
        weight: 10,
      },
      {
        id: 16,
        inputData: "1",
        expectedOutput: "False",
        isHidden: false,
        weight: 15,
      },
      {
        id: 15,
        inputData: "4",
        expectedOutput: "False",
        isHidden: false,
        weight: 15,
      },
      {
        id: 18,
        inputData: "25",
        expectedOutput: "False",
        isHidden: true,
        weight: 10,
      },
      {
        id: 14,
        inputData: "7",
        expectedOutput: "True",
        isHidden: false,
        weight: 15,
      },
      {
        id: 17,
        inputData: "17",
        expectedOutput: "True",
        isHidden: true,
        weight: 10,
      },
    ],
  },
  {
    id: 4,
    title: "Revertir una cadena",
    description:
      "Escribe una función que reciba una cadena y retorne su reverso.",
    starterCode: "def revertir_cadena(cadena):\\n    pass",
    language: "python",
    difficultyLevel: "Principiante",
    sequenceNumber: 4,
    isActive: true,
    createdAt: "2025-06-22T21:01:18.982+00:00",
    testCases: [
      {
        id: 25,
        inputData: "12345",
        expectedOutput: "54321",
        isHidden: true,
        weight: 15,
      },
      {
        id: 23,
        inputData: "a",
        expectedOutput: "a",
        isHidden: false,
        weight: 15,
      },
      {
        id: 26,
        inputData: "Hola Mundo",
        expectedOutput: "odnuM aloH",
        isHidden: true,
        weight: 15,
      },
      {
        id: 22,
        inputData: "python",
        expectedOutput: "nohtyp",
        isHidden: false,
        weight: 20,
      },
      {
        id: 24,
        inputData: "",
        expectedOutput: "",
        isHidden: false,
        weight: 15,
      },
      {
        id: 21,
        inputData: "hola",
        expectedOutput: "aloh",
        isHidden: false,
        weight: 20,
      },
    ],
  },
];
