# .github/workflows/ci.yml
name: Frontend CI - PyAcademy (Testing)

on:
  push:
    branches: [ feature/actions-frontend ]
  pull_request:
    branches: [ frontend, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    #- name: Run ESLint
     # run: npm run lint
    
    #- name: Run tests
     # run: npm run test
    
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production
    