name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: gaspar
          POSTGRES_PASSWORD: armando1gaspar
          POSTGRES_DB: py_academic
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Create uploads directory
      run: mkdir -p ./uploads

    - name: Build and test with Maven
      run: mvn clean test
      env:
        SPRING_APPLICATION_NAME: pyAcademy
        APP_VERSION: 1.0.0
        SERVER_PORT: 8888
        SERVER_SERVLET_CONTEXT_PATH: /api/v1
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/py_academic
        SPRING_DATASOURCE_USERNAME: gaspar
        SPRING_DATASOURCE_PASSWORD: armando1gaspar
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
        SPRING_SECURITY_USER_NAME: softcraft
        SPRING_SECURITY_USER_PASSWORD: softcraft2025
        SECURITY_JWT_KEY_PRIVATE: 22398c3511fc88034d10e15b7ac33a595f7e7764fe78dcabe257ec04edbb7254
        SECURITY_JWT_USER_GENERATOR: AUTH0JWT-BACKEND
        FILE_STORAGE_DIRECTORY: ./uploads

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          **/target/surefire-reports
          **/target/failsafe-reports
          ./logs
